Task_1_2_1
izabellllia/OOP pull request #6
Opened 2023-10-07 16:46 UTC by izabellllia

2023-10-09 09:19 UTC, galinabykova requested changes
может быть, не заметила, но не увидела DFS итератор и удаление. Также есть замечания reviewdog

2023-10-09 09:19 UTC, galinabykova commented on Task_1_2_1/src/main/java/zhitnik/Tree.java
> +class BreadthFirstIterator<T> implements Iterable<Node<T>> {
обычно коллекция сама реализует интерфейс Iterable. Ты можешь объявить Tree Iterable и перенести туда методы этого интерфейса. Интересно, почему ты решила реализовывать так? Тебя смутило, что нужно реализовывать итераторы двух типов?

2023-10-09 09:19 UTC, galinabykova commented on Task_1_2_1/src/main/java/zhitnik/Tree.java
> +class BreadthFirstIterator<T> implements Iterable<Node<T>> {
лучше не называть этот класс Iterator, неочевидно, что это Iterable, а не итератор

2023-10-17 16:16 UTC, galinabykova requested changes
кажется, нет обработки ConcurrentModificationError

2023-10-17 16:16 UTC, galinabykova commented on Task_1_2_1/.idea/.gitignore
удали ненужные файлики

2023-10-17 16:16 UTC, galinabykova commented on Task_1_2_1/src/main/java/zhitnik/Node.java
> +    public void setChildren(List<Node<T>> children) {
ты при итерировании возвращаешь Node, кажется, пользователь может что-то поломать с помощью этого метода, подменив наследников узла. При этом у тебя этот метод не используется, так что я бы его убрала. Если ты решила добавить его осознанно, напиши, почему решила добавить его

2023-10-18 05:42 UTC, galinabykova requested changes

2023-10-18 05:42 UTC, galinabykova commented on Task_1_2_1/src/main/java/zhitnik/TreeIterableBfs.java
> +    private class BreadthFirstIterator<T> implements Iterator<Node<T>> {
кажется, нет обработки ConcurrentModificationError

2023-10-18 15:29 UTC, galinabykova requested changes

2023-10-18 15:29 UTC, galinabykova commented on Task_1_2_1/src/main/java/zhitnik/TreeIterableDfs.java
> +        private int modCount = 0;
можешь объяснить, как оно работает? и сделать тест отлов этой ошибки

2023-10-18 15:29 UTC, galinabykova commented on Task_1_2_1/src/main/java/zhitnik/TreeIterableDfs.java
> +        private int modCount = 0;
есть ощущение, что эта переменная должна быть где-то в дереве, но, возможно, я просто не поняла твоё решение

2023-10-18 15:32 UTC, izabellllia commented on Task_1_2_1/src/main/java/zhitnik/TreeIterableDfs.java
> +        private int modCount = 0;
modCount увеличивается при каждом вызове push(), и ожидаемый expectedModCount обновляется после каждого вызова next(). Если модификация происходит в другом месте во время итерации (то есть, если modCount и expectedModCount не совпадают), то вызывается ConcurrentModificationException.

Но есть ощущение, что все будет хорошо. работать и без это штуки :)))

2023-10-18 15:37 UTC, galinabykova commented on Task_1_2_1/src/main/java/zhitnik/TreeIterableDfs.java
> +        private int modCount = 0;
а если изменение будет происходить не в другом итераторе, а при удалении элемента из дерева (например, removeLeaf)?

2023-10-18 15:43 UTC, izabellllia commented on Task_1_2_1/src/main/java/zhitnik/TreeIterableDfs.java
> +        private int modCount = 0;
тогда будет ошибка...?? removeLeaf изменяет структуру дерева, это приведет к изменению колва операций modCount. Получается, что expectedModCount и modCount больше не будут совпадать в next() или hasNext(), что вызовет ConcurrentModificationException

2023-10-18 15:52 UTC, galinabykova commented on Task_1_2_1/src/main/java/zhitnik/TreeIterableDfs.java
> +        private int modCount = 0;
Мне кажется, у тебя в removeLeaf вызывается другой итератор (итератор списка), который никак не зависит от твоего рукописного. Возможно, я ошибаюсь, сделай тест, в котором будет допущена ConcurrentModificationError и проверь бросится ли исключение ConcurrentModificationException

2023-10-18 17:28 UTC, galinabykova requested changes
reviewdog

2023-10-18 17:44 UTC, galinabykova approved these changes

2023-10-22 07:13 UTC, merged